swagger: "2.0"
info:
  title: "API de propagandas"
  description: "API de documentação para propagandas"
  version: "1.0.0"
host: "192.168.0.84:5050"
schemes:
  - "http"
paths:
  /auth/login:
    post:
      summary: "User login"
      description: "Login to the application"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User credentials"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "Successful login"
        401:
          description: "Invalid username or password"
  /auth/user/create:
    post:
      summary: "Create a user"
      description: "Create a new user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User object"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
              is_admin:
                type: "boolean"
              active:
                type: "boolean"
      security:
        - Bearer: []
      responses:
        201:
          description: "User created"
        400:
          description: "Invalid input"
  /person/create:
    post:
      summary: "Create a person"
      description: "Create a new person"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Person object"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              cpf_cnpj:
                type: "string"
              email:
                type: "string"
              phone:
                type: "string"
              road:
                type: "string"
              state:
                type: "string"
              number:
                type: "string"
              neighborhood:
                type: "string"
              is_employee:
                type: "boolean"
              is_client:
                type: "boolean"
              is_driver:
                type: "boolean"
              user_id:
                type: "integer"
      security:
        - Bearer: []
      responses:
        201:
          description: "Person created"
        400:
          description: "Invalid input"
  /person/list:
    get:
      summary: "List persons"
      description: "Get a list of all persons"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "id"
          type: "integer"
          description: "Filter person by id"
        - in: "query"
          name: "is_client"
          type: "boolean"
          description: "Filter clients"
        - in: "query"
          name: "is_employee"
          type: "boolean"
          description: "Filter employees"
        - in: "query"
          name: "is_driver"
          type: "boolean"
          description: "Filter drivers"
        - in: "query"
          name: "cpf_cnpj"
          type: "string"
          description: "Filter persons by cpf or cnpj"
      security:
        - Bearer: []
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                nome:
                  type: "string"
                cpf:
                  type: "string"
                email:
                  type: "string"
                phone:
                  type: "string"
                road:
                  type: "string"
                state:
                  type: "string"
                number:
                  type: "string"
                neighborhood:
                  type: "string"
                is_employee:
                  type: "boolean"
                is_client:
                  type: "boolean"
                is_driver:
                  type: "boolean"
                active:
                  type: "boolean"
                user_id:
                  type: "integer"
        401:
          description: "Unauthorized"
  /advertising/create:
    post:
      summary: "Create an advertising"
      description: "Create a new advertising"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Advertising object"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              image:
                type: "string"
                format: "byte"
              video_url:
                type: "string"
              person_id:
                type: "integer"
              active:
                type: "boolean"
      security:
        - Bearer: []
      responses:
        201:
          description: "Advertising created"
        400:
          description: "Invalid input"
        404:
          description: "Not found"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer {token}'"
