swagger: "2.0"
info:
  title: "API de Propagandas"
  description: "API de documentação para propagandas"
  version: "1.0.0"
host: "10.10.3.212:5050"
schemes:
  - "http"
tags:
  - name: "Auth"
    description: "Endpoints de autenticação"
  - name: "Person"
    description: "Endpoints para gerenciamento de pessoas"
  - name: "Advertising"
    description: "Endpoints para gerenciamento de propagandas"
paths:
  /auth/login:
    post:
      tags:
        - "Auth"
      summary: "User login"
      description: "Login to the application"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User credentials"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "Successful login"
        401:
          description: "Invalid username or password"
  /auth/user/create:
    post:
      tags:
        - "Auth"
      summary: "Create a user"
      description: "Create a new user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User object"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
              is_admin:
                type: "boolean"
              active:
                type: "boolean"
      security:
        - Bearer: []
      responses:
        201:
          description: "User created"
        400:
          description: "Invalid input"
  /auth/user/list:
    get:
      tags:
        - "Auth"
      summary: "List users"
      description: "Get a list of all users"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "id_user"
          type: "integer"
          description: "Filter user by id"
        - in: "query"
          name: "username"
          type: "string"
          description: "Filter user by username"
      security:
        - Bearer: []
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id_user:
                  type: "integer"
                username:
                  type: "string"
                is_admin:
                  type: "boolean"
                active:
                  type: "boolean"
        401:
          description: "Unauthorized"
  /person/create:
    post:
      tags:
        - "Person"
      summary: "Create a person"
      description: "Create a new person"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Person object"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              cpf_cnpj:
                type: "string"
              email:
                type: "string"
              phone:
                type: "string"
              road:
                type: "string"
              state:
                type: "string"
              city:
                type: "string"
              number:
                type: "string"
              neighborhood:
                type: "string"
              is_employee:
                type: "boolean"
              is_client:
                type: "boolean"
              is_driver:
                type: "boolean"
              user_id:
                type: "integer"
      security:
        - Bearer: []
      responses:
        201:
          description: "Person created"
        400:
          description: "Invalid input"
  /person/list:
    get:
      tags:
        - "Person"
      summary: "List persons"
      description: "Get a list of all persons"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "id"
          type: "integer"
          description: "Filter person by id"
        - in: "query"
          name: "is_client"
          type: "boolean"
          description: "Filter clients"
        - in: "query"
          name: "is_employee"
          type: "boolean"
          description: "Filter employees"
        - in: "query"
          name: "is_driver"
          type: "boolean"
          description: "Filter drivers"
        - in: "query"
          name: "cpf_cnpj"
          type: "string"
          description: "Filter persons by cpf or cnpj"
      security:
        - Bearer: []
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                nome:
                  type: "string"
                cpf:
                  type: "string"
                email:
                  type: "string"
                phone:
                  type: "string"
                road:
                  type: "string"
                state:
                  type: "string"
                number:
                  type: "string"
                neighborhood:
                  type: "string"
                is_employee:
                  type: "boolean"
                is_client:
                  type: "boolean"
                is_driver:
                  type: "boolean"
                active:
                  type: "boolean"
                user_id:
                  type: "integer"
        401:
          description: "Unauthorized"
  /person/update/{person_id}:
    put:
      tags:
        - "Person"
      summary: "Update a person"
      description: "Update a person's information"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "person_id"
          description: "ID of the person to update"
          required: true
          type: "integer"
        - in: "body"
          name: "body"
          description: "Person object with updated data"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              cpf_cnpj:
                type: "string"
              email:
                type: "string"
              phone:
                type: "string"
              road:
                type: "string"
              state:
                type: "string"
              city:
                type: "string"
              number:
                type: "string"
              neighborhood:
                type: "string"
              is_employee:
                type: "boolean"
              is_client:
                type: "boolean"
              is_driver:
                type: "boolean"
              user_id:
                type: "integer"
      security:
        - Bearer: []
      responses:
        200:
          description: "Person updated"
        400:
          description: "Invalid input"
        404:
          description: "Person not found"
  /advertising/create:
    post:
      tags:
        - "Advertising"
      summary: "Create an advertising"
      description: "Create a new advertising"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Advertising object"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              description:
                type: "string"
              image:
                type: "string"
                format: "byte"
              date_start:
                type: "string"
              date_end:
                type: "string"
              video_url:
                type: "string"
              person_id:
                type: "integer"
              active:
                type: "boolean"
      security:
        - Bearer: []
      responses:
        201:
          description: "Advertising created"
        400:
          description: "Invalid input"
        404:
          description: "Not found"
  /advertising/list:
    get:
      tags:
        - "Advertising"
      summary: "List person details"
      description: "Get detailed information of persons"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "name"
          type: "string"
          description: "Filter persons by name"
        - in: "query"
          name: "person_id"
          type: "integer"
          description: "Filter persons by ID"
        - in: "query"
          name: "active"
          type: "boolean"
          description: "Filter persons by active status"
      security:
        - Bearer: []
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                name:
                  type: "string"
                image:
                  type: "string"
                  format: "byte"
                video_url:
                  type: "string"
                person_id:
                  type: "integer"
                active:
                  type: "boolean"
        401:
          description: "Unauthorized"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer {token}'"
